from django.conf.urls import url
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
    path('sitemap.xml', TemplateView.as_view(template_name="sitemap.xml", content_type="text/plain"),),
    path('downloads/', views.download_docs, name='download_docs'),
    path('news/', views.news, name='news'),
    path('category/', views.category, name='category'),
    path('category/<int:category_id>/units', views.engine_units, name='engine_units'),
    path('category/<int:category_id>/units/<int:unit_id>', views.engine_units_parts, name='engine_units_parts'),
    path('category/<int:category_id>/<int:unit_id>/part/<int:part_id>', views.engine_units_part, name='engine_units_part'),
    path('news/<int:news_id>', views.news_full, name='news'),
    path('cart/', views.cart, name='cart'),
    path('moder_add_cat/', views.moder_add_cat, name='moder_add_cat'),
    path('add_category/', views.add_category, name='add_category'),
    path('get_unit_parts/', views.get_unit_parts, name='get_unit_parts'),
    path('bearing/', views.bearing, name='bearing'),
    path('seals/', views.seals, name='seals'),
    path('fuel/', views.fuel, name='fuel'),
    path('sealspump/', views.sealspump, name='sealspump'),
    path('gasket/', views.gasket, name='gasket'),
    path('manufacturing/', views.manufacturing, name='manufacturing'),
    path('development/', views.development, name='development'),
    path('turning/', views.turning, name='turning'),
    path('trade/', views.trade, name='trade'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
    path('geo/', views.geo, name='geo'),
    # path('order/', views.order, name='order'),
    path('product/', views.product, name='product'),
    path('tender/', views.tender, name='tender'),
    path('services/', views.services, name='services'),
    path('about/', views.about, name='about'),
    path('componentcat/', views.componentcat, name='componentcat'),
    path('goodscat/', views.goodscatall, name='goodscat'),
    path('goodscat/<int:good_id>', views.goodscat_card, name='goodscat'),
    path('goodscat/<str:good_type>', views.goodscat, name='goodscat'),
    path('sales/', views.sales, name='sales'),
    path('refresh_discount_goods/', views.refresh_discount_goods, name='refresh_discount_goods'),
    path('new_order_request/', views.new_order_request, name='new_order_request'),
    path('new_tender_request/', views.new_tender_request, name='new_tender_request'),
    path('refresh_perspective_goods/', views.refresh_perspective_goods, name='refresh_perspective_goods'),
    path('refresh_product_price/', views.refresh_product_price, name='refresh_product_price'),
    path('refresh_product_last/', views.refresh_product_last, name='refresh_product_last'),
    path('perspective/', views.perspective, name='perspective'),
    path('bearingcat/', views.bearingcat, name='bearingcat'),
    path('fuelcat/', views.fuelcat, name='fuelcat'),
    path('sealscat/', views.sealscat, name='sealscat'),
    path('sealspumpcat/', views.sealspumpcat, name='sealspumpcat'),
    path('sert/', views.sert, name='sert'),
    path('productslast/', views.productslast, name='productslast'),
    path('productsprice/', views.productsprice, name='productsprice'),
    path('fast_search/', views.fast_search, name='fast_search'),
    path('pdfviewer/<str:uri_pdf>', views.pdfviewer, name='pdfviewer'),
    path('new/upload_img/', views.UploadImage.as_view(), name='imgupload'),
    path('update_units/', views.UpdateImgUnits.as_view(), name='update_units'),
    path('update_parts_info/', views.update_parts_info, name='update_parts_info'),
    #CART
    path('thanks/', views.thanks, name='thanks'),
    path('addtocart/<int:good_id>', views.addtocart, name='addtocart'),
    path('getcart', views.getcart, name='getcart'),
    path('getCartCount', views.getCartCount, name='getCartCount'),
    path('gooddelete/<str:good_id>', views.gooddelete, name='gooddelete'),
    path('changecount/<int:good_id>/<int:good_count>', views.changecount, name='changecount'),
]