# Generated by Django 2.2.7 on 2020-11-01 23:28

import alfa.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufactur', models.CharField(blank=True, max_length=200, verbose_name='Завод производитель')),
                ('series', models.CharField(max_length=200, verbose_name='Серия')),
                ('img', models.ImageField(blank=True, null=True, upload_to=alfa.models.Catalog.get_image_path, verbose_name='Фото')),
                ('scheme', models.ImageField(blank=True, null=True, upload_to=alfa.models.Catalog.get_scheme_path, verbose_name='Схема')),
                ('filePDF', models.FileField(blank=True, default='default_pdf.pdf', null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/karpovdenis/comalfa/media'), upload_to=alfa.models.Catalog.get_filePDF_path, verbose_name='Документ pdf')),
                ('processed', models.BooleanField(default=False, verbose_name='Без пароля и водяного знака')),
                ('HTML_markup', models.TextField(blank=True, help_text='area shape="rect" coords="82,186,101,202" href="#line18" onclick="showHide("#line18");" alt="18"', null=True, verbose_name='HTML разметка для интерактивного изображения')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Позиция')),
                ('notes', models.CharField(blank=True, max_length=600, null=True, verbose_name='Примечание')),
                ('marks', models.CharField(blank=True, max_length=600, null=True, verbose_name='Маркировки')),
                ('guide', models.FileField(upload_to=alfa.models.Catalog.get_guide_path, verbose_name='Документ pdf/excel/word')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('sort_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('multiple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple', to='alfa.Catalog', verbose_name='Состовной элемент')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='alfa.Catalog', verbose_name='Деталь составного элемента')),
            ],
            options={
                'verbose_name': 'Составной элемент',
                'verbose_name_plural': 'Составные элементы',
            },
        ),
    ]
