# Generated by Django 2.2.7 on 2020-11-05 13:51

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('data', models.FileField(upload_to=main.models.Documents.get_image_path, verbose_name='Документ pdf/excel')),
                ('date', models.CharField(blank=True, max_length=30, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление (автозаполнение)')),
            ],
            options={
                'verbose_name': 'Документ (Загрузки)',
                'verbose_name_plural': 'Документы (Загрузки)',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.ImageField(blank=True, null=True, upload_to=main.models.Engine.get_image_path, verbose_name='Схема')),
                ('filePDF', models.FileField(blank=True, default='default_pdf.pdf', null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/karpovdenis/comalfa/media'), upload_to=main.models.Engine.get_filePDF_path, verbose_name='Документ pdf')),
                ('processed', models.BooleanField(default=False, verbose_name='Без пароля и водяного знака')),
            ],
            options={
                'verbose_name': 'Название Двигателя',
                'verbose_name_plural': 'Название Двигателей',
            },
        ),
        migrations.CreateModel(
            name='EngineUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.ImageField(blank=True, upload_to=main.models.EngineUnits.get_image_path, verbose_name='Схема')),
                ('HTML_markup', models.TextField(blank=True, help_text='area shape="rect" coords="82,186,101,202" href="#line18" onclick="showHide("#line18");" alt="18"', null=True, verbose_name='HTML разметка для интерактивного изображения')),
                ('sort_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('engine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Engine', verbose_name='Двигатель')),
            ],
            options={
                'verbose_name': 'Деталь Двигателя',
                'verbose_name_plural': 'Детали Двигателей',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=main.models.Gallery.get_image_path, verbose_name='Изображение')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='MainGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('mark', models.CharField(blank=True, max_length=200, verbose_name='Маркировка')),
                ('status', models.CharField(blank=True, choices=[('Готов', 'Готов'), ('В перспективе', 'В перспективе'), ('Удалено', 'Удалено')], max_length=200, verbose_name='Статус товара')),
                ('type', models.CharField(blank=True, choices=[('Подшипники', 'Подшипники'), ('Уплотнение клапанов', 'Уплотнение клапанов'), ('Компоненты впрыска', 'Компоненты впрыска'), ('Торцевые уплотнения', 'Торцевые уплотнения'), ('Прокладки', 'Прокладки'), ('Другое', 'Другое')], max_length=200, verbose_name='Тип товара')),
                ('using', models.CharField(blank=True, max_length=1500, verbose_name='Применение')),
                ('catalogs', models.CharField(blank=True, max_length=1500, verbose_name='Каталог деталей')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Материал')),
                ('weight', models.CharField(blank=True, max_length=200, verbose_name='Вес')),
                ('analog', models.CharField(blank=True, max_length=400, verbose_name='Аналоги')),
                ('length', models.CharField(blank=True, max_length=400, verbose_name='Размер(мм)')),
                ('quantity_pack', models.CharField(blank=True, max_length=200, verbose_name='Кол-во в упаковке')),
                ('manufactur', models.CharField(blank=True, max_length=200, verbose_name='Изготовитель')),
                ('package', models.CharField(blank=True, max_length=2000, verbose_name='Состав комплекта')),
                ('note', models.CharField(blank=True, max_length=2000, verbose_name='Примечание')),
                ('quantity', models.CharField(blank=True, max_length=10, verbose_name='Количество на складе')),
                ('price', models.CharField(blank=True, max_length=200, verbose_name='Цена без НДС')),
                ('discount', models.CharField(blank=True, max_length=20, verbose_name='Скидка (%)')),
                ('cost', models.CharField(blank=True, max_length=200, verbose_name='Цена со скидкой')),
                ('img', models.ImageField(blank=True, default='good_def_image.jpeg', upload_to=main.models.MainGoods.get_image_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to=main.models.News.get_image_path, verbose_name='Фото')),
                ('date', models.CharField(blank=True, max_length=30, verbose_name='Дата публикации')),
                ('longDescription', models.TextField(verbose_name='Описание')),
                ('shortDescription', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('visible', models.BooleanField(default=True, verbose_name='Показывать новость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='PopularUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to=main.models.PopularUrl.get_image_path, verbose_name='Фото')),
                ('shortDescription', models.CharField(max_length=400, verbose_name='Короткое описание')),
                ('uri', models.CharField(max_length=200, verbose_name='Ссылка на источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление (автозаполнение)')),
            ],
            options={
                'verbose_name': 'Популярное',
                'verbose_name_plural': 'Популярное',
            },
        ),
        migrations.CreateModel(
            name='SeriesEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufactur', models.CharField(blank=True, max_length=200, verbose_name='Завод производитель')),
                ('img', models.ImageField(blank=True, null=True, upload_to=main.models.SeriesEngine.get_image_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Серия двигателя',
                'verbose_name_plural': 'Серия двигателей',
            },
        ),
        migrations.CreateModel(
            name='SeriesEngineGuides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('guide', models.FileField(upload_to=main.models.SeriesEngineGuides.get_image_path, verbose_name='Документ pdf/excel/word')),
                ('processed', models.BooleanField(default=False, verbose_name='Без пароля и водяного знака')),
                ('seriesEngine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SeriesEngine', verbose_name='Серия двигателя')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководства',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Позиция')),
                ('notes', models.CharField(blank=True, max_length=600, null=True, verbose_name='Примечание')),
                ('quantity', models.CharField(blank=True, max_length=6, null=True, verbose_name='Кол-во на двигатель')),
                ('marks', models.CharField(blank=True, max_length=600, null=True, verbose_name='Маркировки')),
                ('part_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EngineUnits', verbose_name='Часть детали')),
            ],
            options={
                'verbose_name': 'Часть детали',
                'verbose_name_plural': 'Части деталей',
            },
        ),
        migrations.AddField(
            model_name='engine',
            name='seriesEngine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SeriesEngine', verbose_name='Серия двигателя'),
        ),
    ]
