# Generated by Django 2.2.7 on 2020-06-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='images', verbose_name='Фото')),
                ('date', models.CharField(blank=True, max_length=30, verbose_name='Дата публикации')),
                ('longDescription', models.TextField(verbose_name='Описание')),
                ('shortDescription', models.CharField(max_length=200, verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
