# Generated by Django 2.2.7 on 2020-06-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('data', models.BinaryField(verbose_name='Документ pdf/excel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Документ (Загрузки)',
                'verbose_name_plural': 'Документы (Загрузки)',
            },
        ),
    ]
