# Generated by Django 2.2.7 on 2020-06-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='data',
            field=models.FileField(upload_to='docs', verbose_name='Документ pdf/excel'),
        ),
    ]
