# Generated by Django 2.2.7 on 2020-06-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200614_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='date',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление (автозаполнение)'),
        ),
    ]
