# Generated by Django 2.2.7 on 2020-06-18 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200614_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufactured', models.CharField(max_length=200, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': 'Двигатели',
            },
        ),
        migrations.CreateModel(
            name='EngineUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('engine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Engine', verbose_name='Двигатель')),
            ],
            options={
                'verbose_name': 'Деталь Двигателя',
                'verbose_name_plural': 'Детали Двигателей',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('position', models.CharField(max_length=200, verbose_name='Позиция')),
                ('notes', models.CharField(max_length=600, verbose_name='Примечание')),
                ('quantity', models.CharField(max_length=6, verbose_name='Кол-во на двигатель')),
                ('marks', models.CharField(max_length=600, verbose_name='Маркировки')),
                ('part_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EngineUnits', verbose_name='Часть детали')),
            ],
            options={
                'verbose_name': 'Часть детали',
                'verbose_name_plural': 'Части деталей',
            },
        ),
    ]
