# Generated by Django 2.2.7 on 2020-06-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_engine_engineunits_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='img',
            field=models.ImageField(null=True, upload_to='Engine_images', verbose_name='Схема'),
        ),
        migrations.AddField(
            model_name='engineunits',
            name='img',
            field=models.ImageField(null=True, upload_to='EngineUnits_images', verbose_name='Схема'),
        ),
    ]
