# Generated by Django 2.2.7 on 2020-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200702_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufactur', models.CharField(blank=True, max_length=200, verbose_name='Завод производитель')),
                ('img', models.ImageField(blank=True, null=True, upload_to='SeriesEngine_images', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Серия двигателя',
                'verbose_name_plural': 'Серия двигателей',
            },
        ),
        migrations.CreateModel(
            name='SeriesEngineGuides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('guide', models.FileField(upload_to='Руководство', verbose_name='Документ pdf/excel/word')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководства',
            },
        ),
    ]
