# Generated by Django 2.2.7 on 2020-07-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_seriesengineguides_seriesengine'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='seriesEngine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SeriesEngine', verbose_name='Серия двигателя'),
        ),
    ]
