# Generated by Django 2.2.7 on 2020-07-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_perspectivegoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='Тип товара')),
                ('using', models.CharField(blank=True, max_length=400, verbose_name='Применение')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Материал')),
                ('weight', models.CharField(blank=True, max_length=200, verbose_name='Цена со скидкой')),
                ('analog', models.CharField(blank=True, max_length=400, verbose_name='Аналоги')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
