# Generated by Django 2.2.7 on 2020-07-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_maingoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingoods',
            name='img',
            field=models.ImageField(blank=True, upload_to='MainGoods_images', verbose_name='Изображение'),
        ),
    ]
