# Generated by Django 2.2.7 on 2020-07-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_maingoods_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingoods',
            name='mark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Маркировка'),
        ),
    ]
