# Generated by Django 2.2.7 on 2020-07-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_maingoods_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelProductLast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('quantity', models.CharField(blank=True, max_length=200, verbose_name='Количество на складе')),
                ('unit', models.CharField(blank=True, max_length=200, verbose_name='Ед.')),
                ('using', models.CharField(blank=True, max_length=200, verbose_name='Применение')),
                ('group', models.CharField(blank=True, max_length=200, verbose_name='Группа')),
                ('manufactur', models.CharField(blank=True, max_length=200, verbose_name='Завод производитель')),
            ],
        ),
        migrations.CreateModel(
            name='ExcelProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('unit', models.CharField(blank=True, max_length=200, verbose_name='Ед.')),
                ('priceNoNDS', models.CharField(blank=True, max_length=200, verbose_name='Цена без НДС')),
                ('using', models.CharField(blank=True, max_length=200, verbose_name='Применение')),
                ('group', models.CharField(blank=True, max_length=200, verbose_name='Группа')),
            ],
        ),
        migrations.AlterField(
            model_name='maingoods',
            name='type',
            field=models.CharField(blank=True, choices=[('Подшипники', 'Подшипники'), ('Уплотнение клапанов', 'Уплотнение клапанов'), ('Компоненты впрыска', 'Компоненты впрыска'), ('Торцевые уплотнения', 'Торцевые уплотнения'), ('Прокладки', 'Прокладки')], max_length=200, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='maingoods',
            name='weight',
            field=models.CharField(blank=True, max_length=200, verbose_name='Вес'),
        ),
    ]
