# Generated by Django 2.2.7 on 2020-07-24 01:22

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200722_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesengineguides',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='data',
            field=models.FileField(upload_to=main.models.Documents.get_image_path, verbose_name='Документ pdf/excel'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Engine.get_image_path, verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='engineunits',
            name='img',
            field=models.ImageField(blank=True, upload_to=main.models.EngineUnits.get_image_path, verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(upload_to=main.models.Gallery.get_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='maingoods',
            name='img',
            field=models.ImageField(blank=True, upload_to=main.models.MainGoods.get_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to=main.models.News.get_image_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='seriesengine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.SeriesEngine.get_image_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='seriesengineguides',
            name='guide',
            field=models.FileField(upload_to=main.models.SeriesEngineGuides.get_image_path, verbose_name='Документ pdf/excel/word'),
        ),
    ]
