# Generated by Django 2.2.7 on 2020-07-24 02:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200724_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='filePDF',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Engine.get_filePDF_path, verbose_name='PDF файл'),
        ),
        migrations.AddField(
            model_name='engine',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
