# Generated by Django 2.2.7 on 2020-07-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200724_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='filePDF',
        ),
    ]
