# Generated by Django 2.2.7 on 2020-07-24 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_engine_filepdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='filePDF',
        ),
    ]
