# Generated by Django 2.2.7 on 2020-07-24 02:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_engine_filepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='filePDF',
            field=models.FileField(blank=True, null=True, upload_to=main.models.Engine.get_filePDF_path, verbose_name='Документ pdf'),
        ),
    ]
