# Generated by Django 2.2.7 on 2020-07-27 01:09

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_engine_filepdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to=main.models.PopularUrl.get_image_path, verbose_name='Фото')),
                ('shortDescription', models.CharField(max_length=400, verbose_name='Короткое описание')),
                ('uri', models.CharField(max_length=200, verbose_name='Ссылка на источник')),
            ],
            options={
                'verbose_name': 'Популярное',
                'verbose_name_plural': 'Популярное',
            },
        ),
    ]
