# Generated by Django 2.2.7 on 2020-07-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_popularurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineunits',
            name='HTML_markup',
            field=models.TextField(blank=True, null=True, verbose_name='HTML разметка для интерактивного изображения'),
        ),
    ]
