# Generated by Django 2.2.7 on 2020-07-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_engineunits_html_markup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineunits',
            name='HTML_markup',
            field=models.TextField(blank=True, help_text='<area shape="rect" coords="82,186,101,202" href="#line18" onclick="showHide("#line18");" alt="18">', null=True, verbose_name='HTML разметка для интерактивного изображения'),
        ),
    ]
