# Generated by Django 2.2.7 on 2020-07-30 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200728_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавление (автозаполнение)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engineunits',
            name='HTML_markup',
            field=models.TextField(blank=True, help_text='area shape="rect" coords="82,186,101,202" href="#line18" onclick="showHide("#line18");" alt="18"', null=True, verbose_name='HTML разметка для интерактивного изображения'),
        ),
    ]
