# Generated by Django 2.2.7 on 2020-08-12 12:23

import django.core.files.storage
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200812_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='filePDF',
            field=models.FileField(blank=True, default='images/6png.png', null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/sammy/comalfa/media'), upload_to=main.models.Engine.get_filePDF_path, verbose_name='Документ pdf'),
        ),
    ]
