# Generated by Django 2.2.7 on 2020-08-23 23:50

import django.core.files.storage
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200812_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountgoods',
            name='group',
            field=models.CharField(blank=True, max_length=200, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='discountgoods',
            name='manufactur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Завод производитель'),
        ),
        migrations.AddField(
            model_name='discountgoods',
            name='mark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Маркировка'),
        ),
        migrations.AddField(
            model_name='discountgoods',
            name='using',
            field=models.CharField(blank=True, max_length=400, verbose_name='Применение'),
        ),
        migrations.AddField(
            model_name='excelproductlast',
            name='mark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Маркировка'),
        ),
        migrations.AddField(
            model_name='excelproductprice',
            name='manufactur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Завод производитель'),
        ),
        migrations.AddField(
            model_name='excelproductprice',
            name='mark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Маркировка'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='filePDF',
            field=models.FileField(blank=True, default='default_pdf.pdf', null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/dimadev/comalfa/media'), upload_to=main.models.Engine.get_filePDF_path, verbose_name='Документ pdf'),
        ),
    ]
