# Generated by Django 2.2.7 on 2020-08-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200823_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AddField(
            model_name='maingoods',
            name='length',
            field=models.CharField(blank=True, max_length=400, verbose_name='Размер(мм)'),
        ),
        migrations.AddField(
            model_name='maingoods',
            name='manufactur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Изготовитель'),
        ),
        migrations.AddField(
            model_name='maingoods',
            name='note',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='maingoods',
            name='package',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Состав комплекта'),
        ),
        migrations.AddField(
            model_name='maingoods',
            name='quantity_pack',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кол-во в упаковке'),
        ),
    ]
