# Generated by Django 2.2.7 on 2020-08-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200828_2046'),
        ('main', '0037_auto_20200823_2358'),
    ]

    operations = [
    ]
