# Generated by Django 2.2.7 on 2020-09-15 02:58

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200828_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineunits',
            name='sort_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='maingoods',
            name='catalogs',
            field=models.CharField(blank=True, max_length=800, verbose_name='Каталог деталей'),
        ),
        migrations.AddField(
            model_name='maingoods',
            name='price',
            field=models.CharField(blank=True, max_length=200, verbose_name='Цена без НДС'),
        ),
        migrations.AddField(
            model_name='maingoods',
            name='quantity',
            field=models.CharField(blank=True, max_length=10, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='maingoods',
            name='img',
            field=models.ImageField(blank=True, default='good_def_image.jpeg', upload_to=main.models.MainGoods.get_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='maingoods',
            name='using',
            field=models.CharField(blank=True, max_length=800, verbose_name='Применение'),
        ),
    ]
