# Generated by Django 2.2.7 on 2020-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_merge_20200828_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingoods',
            name='quantity',
            field=models.CharField(blank=True, max_length=10, verbose_name='Количество на складе'),
        ),
    ]
