# Generated by Django 2.2.7 on 2020-09-03 00:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_engineunits_sort_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingoods',
            name='price',
            field=models.CharField(blank=True, max_length=200, verbose_name='Цена без НДС'),
        ),
        migrations.AlterField(
            model_name='maingoods',
            name='img',
            field=models.ImageField(blank=True, default='good_def_image.jpeg', upload_to=main.models.MainGoods.get_image_path, verbose_name='Изображение'),
        ),
    ]
