# Generated by Django 2.2.7 on 2020-09-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200915_0258'),
        ('main', '0041_auto_20200903_0006'),
    ]

    operations = [
    ]
