# Generated by Django 2.2.7 on 2020-09-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_merge_20200919_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountGoods',
        ),
        migrations.DeleteModel(
            name='ExcelProductLast',
        ),
        migrations.DeleteModel(
            name='ExcelProductPrice',
        ),
        migrations.DeleteModel(
            name='PerspectiveGoods',
        ),
        migrations.RemoveField(
            model_name='maingoods',
            name='catalogs',
        ),
    ]
