# Generated by Django 2.2.7 on 2020-09-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200919_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingoods',
            name='catalogs',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Каталог деталей'),
        ),
        migrations.AlterField(
            model_name='maingoods',
            name='using',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Применение'),
        ),
    ]
