# Generated by Django 2.2.7 on 2020-09-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20200919_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingoods',
            name='cost',
            field=models.CharField(blank=True, max_length=200, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='maingoods',
            name='discount',
            field=models.CharField(blank=True, max_length=20, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='maingoods',
            name='status',
            field=models.CharField(blank=True, choices=[('Готов', 'Готов'), ('В перспективе', 'В перспективе'), ('Удалено', 'Удалено')], max_length=200, verbose_name='Статус товара'),
        ),
        migrations.AlterField(
            model_name='maingoods',
            name='type',
            field=models.CharField(blank=True, choices=[('Подшипники', 'Подшипники'), ('Уплотнение клапанов', 'Уплотнение клапанов'), ('Компоненты впрыска', 'Компоненты впрыска'), ('Торцевые уплотнения', 'Торцевые уплотнения'), ('Прокладки', 'Прокладки'), ('Другое', 'Другое')], max_length=200, verbose_name='Тип товара'),
        ),
    ]
