# Generated by Django 2.2.7 on 2020-11-01 23:28

import django.core.files.storage
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20200920_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engine',
            options={'verbose_name': 'Название Двигателя', 'verbose_name_plural': 'Название Двигателей'},
        ),
        migrations.AlterField(
            model_name='engine',
            name='filePDF',
            field=models.FileField(blank=True, default='default_pdf.pdf', null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/karpovdenis/comalfa/media'), upload_to=main.models.Engine.get_filePDF_path, verbose_name='Документ pdf'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Без пароля и водяного знака'),
        ),
        migrations.AlterField(
            model_name='seriesengineguides',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Без пароля и водяного знака'),
        ),
    ]
